experiment:
  cuda: true
  name: seq121
  seed: 88
  save_logs: ../logs/
  save_checkpoints: ../checkpoints/


data: 
  annotations: ../data/train/train_5fold.csv
  data_dir: ../data/train-refiner/
  outer_fold: 0
  positives_only: true
  targets: pe_present_on_image
  dataset:
    name: PEProbDataset
    params:
      return_weight: true


model:
  name: PEProbRefiner
  params:
    num_classes: 1
    dim: 65
    dropout: 0.2


loss:
  name: PEProbRefineLoss
  params:


optimizer:
  name: RAdam
  params:
    lr: 1.0e-2
    weight_decay: 5.0e-4


scheduler: 
  name: CosineAnnealingLR
  params:
    final_lr: 1.0e-8


train:
  batch_size: 512
  name: Trainer
  params:
    num_epochs: 12
    steps_per_epoch: 0
    validate_interval: 1
    gradient_accumulation: 1
    amp: true


evaluate: 
  batch_size: 1
  name: Evaluator
  params:
    metrics: [loss, auc]
    valid_metric: loss
    mode: min
    improve_thresh: 1.0e-4
    save_best: true


