experiment:
  cuda: true
  name: seq100
  seed: 88
  save_logs: ../logs/
  save_checkpoints: ../checkpoints/


data: 
  annotations: ../data/train/train_kfold.csv
  data_dir: ../data/train-features/
  inner_fold: 0
  outer_fold: 0
  targets: pe_present_on_image
  dataset:
    name: FeatureDataset
    params:
      seq_len: 256
      resample: true


model:
  name: Transformer
  params:
    num_classes: 1
    seq_len: 256
    sequence_cls: true


loss:
  name: CombinedSliceSeriesBCE
  params:


optimizer:
  name: RAdam
  params:
    lr: 1.0e-3
    weight_decay: 5.0e-4


scheduler: 
  name: CosineAnnealingLR
  params:
    final_lr: 1.0e-8


train:
  batch_size: 32
  name: Trainer
  params:
    num_epochs: 5
    steps_per_epoch: 0
    validate_interval: 1
    gradient_accumulation: 1
    amp: true


evaluate: 
  batch_size: 1
  name: Evaluator
  params:
    metrics: [loss, auc]
    valid_metric: loss
    mode: min
    improve_thresh: 1.0e-4
    save_best: true


