experiment:
  cuda: true
  name: heart024
  seed: 88
  save_logs: ../logs/
  save_checkpoints: ../checkpoints/


data: 
  annotations: ../data/train/train_5fold_with_probas.csv
  data_dir: ../data/train/
  outer_fold: 0
  targets: 
    - rv_lv_ratio_gte_1
    - rv_lv_ratio_lt_1
  positives_only: true
  dataset:
    name: SeriesDataset
    params:
      window: [50, 350]
      flip: false
      random_hu: 5
      verbose: true
      repeat_3ch: true
      num_slices: 128


transform:
  resize:
    name: resize_alt
    params:
      imsize: [160, 160]
  augment:
    name: rand_albumentations
    params:
      n: 3
      p: 0.9
  crop:
    name: crop
    params:
      imsize: [140, 140]
  preprocess:
    name: Preprocessor
    params:
      image_range: [0, 255]
      input_range: [0, 1]
      mean: [0.5, 0.5, 0.5]
      sdev: [0.5, 0.5, 0.5]


model:
  name: Net3D
  params:
    backbone: ip_csn_101
    pretrained: true
    num_classes: 2
    dropout: 0.2
    multisample_dropout: true


loss:
  name: RVLVLogLoss
  params:


optimizer:
  name: AdamW
  params:
    lr: 1.0e-4
    weight_decay: 5.0e-4


scheduler: 
  name: CosineAnnealingLR
  params:
    final_lr: 1.0e-6


train:
  batch_size: 8
  name: Trainer
  params:
    num_epochs: 5
    steps_per_epoch: 0
    validate_interval: 1
    gradient_accumulation: 1
    amp: true
    verbosity: 0


evaluate: 
  name: Evaluator
  params:
    metrics: [loss, auc]
    valid_metric: loss
    mode: min
    improve_thresh: 1.0e-4
    save_best: true


