experiment:
  cuda: true
  name: predict009


models:
  pe_feature_extractor:
    - configs/mks/mk013.yaml
    - configs/mks/mk013.yaml
  pe_exam_classifier:
    # Fold 0
    - configs/seq/seq103.yaml
    - configs/seq/seq103b.yaml
    - configs/seq/seq103c.yaml
    # Fold 1
    - configs/seq/seq103.yaml
    - configs/seq/seq103b.yaml
    - configs/seq/seq103c.yaml
  pe_slice_classifier:
    # Fold 0
    - configs/seq/seq112.yaml
    - configs/seq/seq112b.yaml
    - configs/seq/seq112c.yaml
    # Fold 1
    - configs/seq/seq112.yaml
    - configs/seq/seq112b.yaml
    - configs/seq/seq112c.yaml
  pe_exam_tdcnn:
    - configs/mk3d/mk3d008.yaml
    - configs/mk3d/mk3d008.yaml
    - configs/mk3d/mk3d008.yaml
    - configs/mk3d/mk3d008.yaml
  heart_slice_classifier:
    - configs/love/love003.yaml
  rvlv_exam_classifier:
    - configs/heart/heart018.yaml
    - configs/heart/heart018.yaml
    - configs/heart/heart018.yaml
    - configs/heart/heart018.yaml
  rvlv_exam_linear:
    - configs/prob/prob004.yaml
    - configs/prob/prob004.yaml
    - configs/prob/prob004.yaml
    - configs/prob/prob004.yaml


checkpoints:
  pe_feature_extractor:
    - ../checkpoints/mk013/fold0/NET2D_004_VM-0.0611.PTH
    - ../checkpoints/mk013/fold1/NET2D_004_VM-0.0595.PTH
  pe_exam_classifier:
    # Fold 0
    - ../checkpoints/seq103/fold0/TRANSFORMERCLS_007_VM-0.1625.PTH
    - ../checkpoints/seq103b/fold0/TRANSFORMERCLS_008_VM-0.1620.PTH
    - ../checkpoints/seq103c/fold0/TRANSFORMERCLS_009_VM-0.1620.PTH
    # Fold 1
    - ../checkpoints/seq103/fold1/TRANSFORMERCLS_009_VM-0.1530.PTH
    - ../checkpoints/seq103b/fold1/TRANSFORMERCLS_009_VM-0.1522.PTH
    - ../checkpoints/seq103c/fold1/TRANSFORMERCLS_009_VM-0.1537.PTH
  pe_slice_classifier:
    # Fold 0
    - ../checkpoints/seq112/fold0/TRANSFORMER_009_VM-0.2195.PTH
    - ../checkpoints/seq112b/fold0/TRANSFORMER_010_VM-0.2204.PTH
    - ../checkpoints/seq112c/fold0/TRANSFORMER_005_VM-0.2218.PTH
    # Fold 1
    - ../checkpoints/seq112/fold1/TRANSFORMER_009_VM-0.2067.PTH
    - ../checkpoints/seq112b/fold1/TRANSFORMER_011_VM-0.2063.PTH
    - ../checkpoints/seq112c/fold1/TRANSFORMER_010_VM-0.2104.PTH
  pe_exam_tdcnn:
    - ../checkpoints/mk3d008/fold0/TDCNN_009_VM-0.1629.PTH
    - ../checkpoints/mk3d008/fold1/TDCNN_009_VM-0.1588.PTH
    - ../checkpoints/mk3d008/fold2/TDCNN_009_VM-0.1641.PTH
    - ../checkpoints/mk3d008/fold3/TDCNN_007_VM-0.1706.PTH
  heart_slice_classifier:
    - ../checkpoints/love003/fold0/MSNET2D_001_VM-0.9987.PTH
  rvlv_exam_classifier:
    - ../checkpoints/heart018/fold0/NET3D_003_VM-0.4484.PTH
    - ../checkpoints/heart018/fold1/NET3D_004_VM-0.4444.PTH
    - ../checkpoints/heart018/fold2/NET3D_004_VM-0.4695.PTH
    - ../checkpoints/heart018/fold3/NET3D_004_VM-0.4745.PTH
  rvlv_exam_linear:
    - ../checkpoints/prob004/fold0/HEARTFEATURE_009_VM-0.2218.PTH
    - ../checkpoints/prob004/fold1/HEARTFEATURE_007_VM-0.2251.PTH
    - ../checkpoints/prob004/fold2/HEARTFEATURE_009_VM-0.2357.PTH
    - ../checkpoints/prob004/fold3/HEARTFEATURE_009_VM-0.2409.PTH

  
evaluate:
  batch_size: 1


data: 
  annotations: ../data/test/test.csv
  data_dir: ../data/test/
