experiment:
  cuda: true
  name: predict002


models:
  pe_feature_extractor:
    - configs/mks/mk013.yaml
    - configs/mks/mk013.yaml
    - configs/mks/mk013.yaml
    - configs/mks/mk013.yaml
    - configs/mks/mk013.yaml
  pe_exam_classifier:
    - configs/seq/seq103.yaml
    - configs/seq/seq103.yaml
    - configs/seq/seq103.yaml
    - configs/seq/seq103.yaml
    - configs/seq/seq103.yaml
  pe_slice_classifier:
    - configs/seq/seq104.yaml
    - configs/seq/seq104.yaml
    - configs/seq/seq104.yaml
    - configs/seq/seq104.yaml
    - configs/seq/seq104.yaml
  heart_slice_classifier:
    - configs/love/love003.yaml
  rvlv_exam_classifier:
    - configs/heart/heart018.yaml
    - configs/heart/heart018.yaml
    - configs/heart/heart018.yaml
    - configs/heart/heart018.yaml
    - configs/heart/heart018.yaml
  rvlv_exam_linear:
    - configs/prob/prob000.yaml
    - configs/prob/prob000.yaml
    - configs/prob/prob000.yaml
    - configs/prob/prob000.yaml
    - configs/prob/prob000.yaml


checkpoints:
  pe_feature_extractor:
    - ../checkpoints/mk013/fold0/NET2D_004_VM-0.0611.PTH
    - ../checkpoints/mk013/fold1/NET2D_004_VM-0.0595.PTH
    - ../checkpoints/mk013/fold2/NET2D_004_VM-0.0627.PTH
    - ../checkpoints/mk013/fold3/NET2D_004_VM-0.0619.PTH
    - ../checkpoints/mk013/fold4/NET2D_004_VM-0.0652.PTH
  pe_exam_classifier:
    - ../checkpoints/seq103/fold0/TRANSFORMERCLS_007_VM-0.1625.PTH
    - ../checkpoints/seq103/fold1/TRANSFORMERCLS_009_VM-0.1530.PTH
    - ../checkpoints/seq103/fold2/TRANSFORMERCLS_007_VM-0.1625.PTH
    - ../checkpoints/seq103/fold3/TRANSFORMERCLS_007_VM-0.1586.PTH
    - ../checkpoints/seq103/fold4/TRANSFORMERCLS_009_VM-0.1536.PTH
  pe_slice_classifier:
    - ../checkpoints/seq105/fold0/TRANSFORMER_006_VM-0.1860.PTH
    - ../checkpoints/seq105/fold1/TRANSFORMER_005_VM-0.1831.PTH
    - ../checkpoints/seq105/fold2/TRANSFORMER_006_VM-0.1924.PTH
    - ../checkpoints/seq105/fold3/TRANSFORMER_006_VM-0.1930.PTH
    - ../checkpoints/seq105/fold4/TRANSFORMER_005_VM-0.1914.PTH
  heart_slice_classifier:
    - ../checkpoints/love003/fold0/MSNET2D_001_VM-0.9987.PTH
  rvlv_exam_classifier:
    - ../checkpoints/heart018/fold0/NET3D_003_VM-0.4484.PTH
    - ../checkpoints/heart018/fold1/NET3D_004_VM-0.4444.PTH
    - ../checkpoints/heart018/fold2/NET3D_004_VM-0.4695.PTH
    - ../checkpoints/heart018/fold3/NET3D_004_VM-0.4745.PTH
    - ../checkpoints/heart018/fold4/NET3D_004_VM-0.4837.PTH
  rvlv_exam_linear:
    - ../checkpoints/prob000/fold0/SIMPLELINEAR_049_VM-0.2501.PTH
    - ../checkpoints/prob000/fold1/SIMPLELINEAR_049_VM-0.2454.PTH
    - ../checkpoints/prob000/fold2/SIMPLELINEAR_049_VM-0.2682.PTH
    - ../checkpoints/prob000/fold3/SIMPLELINEAR_049_VM-0.2635.PTH
    - ../checkpoints/prob000/fold4/SIMPLELINEAR_049_VM-0.2683.PTH


evaluate:
  batch_size: 1


data: 
  annotations: ../data/test/test_fold0.csv
  data_dir: ../data/train/

