experiment:
  cuda: true
  name: predict100


models:
  pe_feature_extractor:
    - /kaggle/input/rsna-str-pe-src/configs/mks/mk013.yaml
    - /kaggle/input/rsna-str-pe-src/configs/mks/mk013.yaml
    - /kaggle/input/rsna-str-pe-src/configs/mks/mk013.yaml
    - /kaggle/input/rsna-str-pe-src/configs/mks/mk013.yaml
  pe_exam_classifier:
    - /kaggle/input/rsna-str-pe-src/configs/seq/seq103.yaml
    - /kaggle/input/rsna-str-pe-src/configs/seq/seq103.yaml
    - /kaggle/input/rsna-str-pe-src/configs/seq/seq103.yaml
    - /kaggle/input/rsna-str-pe-src/configs/seq/seq103.yaml
  pe_slice_classifier:
    - /kaggle/input/rsna-str-pe-src/configs/seq/seq105.yaml
    - /kaggle/input/rsna-str-pe-src/configs/seq/seq105.yaml
    - /kaggle/input/rsna-str-pe-src/configs/seq/seq105.yaml
    - /kaggle/input/rsna-str-pe-src/configs/seq/seq105.yaml
  heart_slice_classifier:
    - /kaggle/input/rsna-str-pe-src/configs/love/love003.yaml
  rvlv_exam_classifier:
    - /kaggle/input/rsna-str-pe-src/configs/heart/heart018.yaml
    - /kaggle/input/rsna-str-pe-src/configs/heart/heart018.yaml
    - /kaggle/input/rsna-str-pe-src/configs/heart/heart018.yaml
    - /kaggle/input/rsna-str-pe-src/configs/heart/heart018.yaml
    - /kaggle/input/rsna-str-pe-src/configs/heart/heart018.yaml
  rvlv_exam_linear:
    - /kaggle/input/rsna-str-pe-src/configs/prob/prob000.yaml
    - /kaggle/input/rsna-str-pe-src/configs/prob/prob000.yaml
    - /kaggle/input/rsna-str-pe-src/configs/prob/prob000.yaml
    - /kaggle/input/rsna-str-pe-src/configs/prob/prob000.yaml
    - /kaggle/input/rsna-str-pe-src/configs/prob/prob000.yaml


checkpoints:
  pe_feature_extractor:
    - /kaggle/input/rsna-str-pe-checkpoints/mk013/fold0/NET2D_004_VM-0.0611.PTH
    - /kaggle/input/rsna-str-pe-checkpoints/mk013/fold1/NET2D_004_VM-0.0595.PTH
    - /kaggle/input/rsna-str-pe-checkpoints/mk013/fold2/NET2D_004_VM-0.0627.PTH
    - /kaggle/input/rsna-str-pe-checkpoints/mk013/fold3/NET2D_004_VM-0.0619.PTH
  pe_exam_classifier:
    - /kaggle/input/rsna-str-pe-checkpoints/seq103/fold0/TRANSFORMERCLS_007_VM-0.1625.PTH
    - /kaggle/input/rsna-str-pe-checkpoints/seq103/fold1/TRANSFORMERCLS_009_VM-0.1530.PTH
    - /kaggle/input/rsna-str-pe-checkpoints/seq103/fold2/TRANSFORMERCLS_007_VM-0.1625.PTH
    - /kaggle/input/rsna-str-pe-checkpoints/seq103/fold3/TRANSFORMERCLS_007_VM-0.1586.PTH
  pe_slice_classifier:
    - /kaggle/input/rsna-str-pe-checkpoints/seq105/fold0/TRANSFORMER_006_VM-0.1860.PTH
    - /kaggle/input/rsna-str-pe-checkpoints/seq105/fold1/TRANSFORMER_005_VM-0.1831.PTH
    - /kaggle/input/rsna-str-pe-checkpoints/seq105/fold2/TRANSFORMER_006_VM-0.1924.PTH
    - /kaggle/input/rsna-str-pe-checkpoints/seq105/fold3/TRANSFORMER_006_VM-0.1930.PTH
  heart_slice_classifier:
    - /kaggle/input/rsna-str-pe-checkpoints/love003/fold0/MSNET2D_001_VM-0.9987.PTH
  rvlv_exam_classifier:
    - /kaggle/input/rsna-str-pe-checkpoints/heart018/fold0/NET3D_003_VM-0.4484.PTH
    - /kaggle/input/rsna-str-pe-checkpoints/heart018/fold1/NET3D_004_VM-0.4444.PTH
    - /kaggle/input/rsna-str-pe-checkpoints/heart018/fold2/NET3D_004_VM-0.4695.PTH
    - /kaggle/input/rsna-str-pe-checkpoints/heart018/fold3/NET3D_004_VM-0.4745.PTH
    - /kaggle/input/rsna-str-pe-checkpoints/heart018/fold4/NET3D_004_VM-0.4837.PTH
  rvlv_exam_linear:
    - /kaggle/input/rsna-str-pe-checkpoints/prob000/fold0/SIMPLELINEAR_049_VM-0.2501.PTH
    - /kaggle/input/rsna-str-pe-checkpoints/prob000/fold1/SIMPLELINEAR_049_VM-0.2454.PTH
    - /kaggle/input/rsna-str-pe-checkpoints/prob000/fold2/SIMPLELINEAR_049_VM-0.2682.PTH
    - /kaggle/input/rsna-str-pe-checkpoints/prob000/fold3/SIMPLELINEAR_049_VM-0.2635.PTH
    - /kaggle/input/rsna-str-pe-checkpoints/prob000/fold4/SIMPLELINEAR_049_VM-0.2683.PTH


evaluate:
  batch_size: 1


data: 
  annotations: /kaggle/input/rsna-str-pulmonary-embolism-detection/test.csv
  data_dir: /kaggle/input/rsna-str-pulmonary-embolism-detection/test/